export const REQUEST = {
  PENDING: 'REQUEST_PENDING',
  RECEIVED: 'REQUEST_RECEIVED',
  FAILURED: 'REQUEST_FAILURED',
};

export const TOGGLE_MENU = {
  SHOW: 'SHOW_MENU',
  HIDE: 'HIDE_MENU',
};

export const GET_USER = {
  PENDING: 'GET_USER_PENDING',
  RECEIVED: 'GET_USER_RECEIVED',
  FAILURED: 'GET_USER_FAILURED',
};

export const UPDATE_USER = {
  PENDING: 'UPDATE_USER_PENDING',
  RECEIVED: 'UPDATE_USER_RECEIVED',
  FAILURED: 'UPDATE_USER_FAILURED',
};

export const UPLOAD_AVATAR = {
  PENDING: 'UPLOAD_AVATAR_PENDING',
  RECEIVED: 'UPLOAD_AVATAR_RECEIVED',
  FAILURED: 'UPLOAD_AVATAR_FAILURED',
}

export const GET_NETWORKS = {
  PENDING: 'GET_NETWORKS_PENDING',
  RECEIVED: 'GET_NETWORKS_RECEIVED',
  FAILURED: 'GET_NETWORKS_FAILURED',
}

export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE';
export const UPDATE_USER_POINT = 'UPDATE_USER_POINT';
export const UPDATE_USER_PHONE = 'UPDATE_USER_PHONE';


export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
